# The URL the site will be built for
base_url = "https://kadler.io"

title = "Korinne's Ramblings"
description = "Ramblings of an Open Source chick working on IBM i."

theme = "terminimal"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    {name = "tags"},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "nyx-bold"

render_emoji = true

[extra]
# Put all your custom variables here

# Whether to show links to earlier and later posts
# on each post page (defaults to true).
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
# Defaults to "Thanks for reading! Read other posts?"
post_view_navigation_prompt = "Read more"

accent_color = "pink"

logo_text = "Korinne's Ramblings"
author = "Korinne Adler"

social_items = [
    {label = "GitHub", icon = "fab fa-fw fa-github", url = "https://github.com/kadler"},
    {label = "Mastodon", icon = "fab fa-fw fa-mastodon", url = "https://tech.lgbt/@kadler"},
    {label = "Twitter", icon = "fab fa-fw fa-twitter-square", url = "https://twitter.com/kadlerio"},
    {label = "Stack Overflow", icon = "fab fa-fw fa-stack-overflow", url = "https://stackoverflow.com/users/3245633"},
    {label = "LinkedIn", icon = "fab fa-fw fa-linkedin", url = "https://www.linkedin.com/in/kadlerio"},
    {label = "BitBucket", icon = "fab fa-fw fa-bitbucket", url = "https://bitbucket.org/kadler"},
    {label = "GitLab", icon = "fab fa-fw fa-gitlab", url = "https://gitlab.com/kadler"},
]

menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    #{name = "blog", url = "$BASE_URL"},
    
    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details
    {name = "blog", url = "$BASE_URL/blog"},
    {name = "tags", url = "$BASE_URL/tags"},
    #{name = "archive", url = "$BASE_URL/archive"},
    {name = "about", url = "$BASE_URL/about"},
    {name = "ebcdic", url = "$BASE_URL/ebcdic"},
    
    # set newtab to true to make the link open in new tab
    {name = "github", url = "https://github.com/kadler", newtab = true},
]
