name: Jekyll Deploy

on:
  push:
    branches:
      - source
  schedule:
    - cron: "0 18 * * *"

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Set up Bundler and Dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Build the site
        run: bundle exec jekyll build
        env:
          TZ: UTC
      - name: Deploy to GitHub Pages
        env:
           GH_PAGES_TOKEN: ${{ secrets. GH_PAGES_TOKEN }}
        run: |
          cd _site
          git init
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m 'Action build'
          git push --force "https://x-access-token:${GH_PAGES_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master:master
