name: Jekyll Deploy

on:
  push:
    branches:
      - source
  schedule:
    - cron: "0 18 * * *"

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
          ruby-version: '3.0'
          bundler-cache: true
      - name: Build the site
        run: |
          bundle exec jekyll build
          cp CNAME _site
        env:
          TZ: UTC
      - name: Deploy to GitHub Pages
        env:
           GH_PAGES_TOKEN: ${{ secrets. GH_PAGES_TOKEN }}
        run: |
          cd _site
          git init
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m 'Action build'
          git push --force "https://x-access-token:${GH_PAGES_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master:master
